config/routes.rb
Rails.application.routes.draw do
  resources :characters
  get '/characters/by_race/:race_id' => 'characters#by_race'
  resources :sub_class_jobs
  resources :class_jobs
  resources :backgrounds
  resources :sub_races
  resources :races
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/background.rb
class Background < ApplicationRecord
    has_many :characters
end

app/controllers/backgrounds_controller.rb
class BackgroundsController < ApplicationController
  before_action :set_background, only: %i[ show edit update destroy ]

  # GET /backgrounds or /backgrounds.json
  def index
    @backgrounds = Background.all
  end

  # GET /backgrounds/1 or /backgrounds/1.json
  def show
  end

  # GET /backgrounds/new
  def new
    @background = Background.new
  end

  # GET /backgrounds/1/edit
  def edit
  end

  # POST /backgrounds or /backgrounds.json
  def create
    @background = Background.new(background_params)

    respond_to do |format|
      if @background.save
        format.html { redirect_to @background, notice: "Background was successfully created." }
        format.json { render :show, status: :created, location: @background }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @background.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backgrounds/1 or /backgrounds/1.json
  def update
    respond_to do |format|
      if @background.update(background_params)
        format.html { redirect_to @background, notice: "Background was successfully updated." }
        format.json { render :show, status: :ok, location: @background }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @background.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backgrounds/1 or /backgrounds/1.json
  def destroy
    @background.destroy
    respond_to do |format|
      format.html { redirect_to backgrounds_url, notice: "Background was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_background
      @background = Background.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def background_params
      params.require(:background).permit(:name)
    end
end

app/helpers/backgrounds_helper.rb
module BackgroundsHelper
end

app/views/backgrounds/_form.html.erb
<%= form_for @background, :html => { :class => "form-horizontal background" } do |f| %>

  <% if @background.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@background.errors.count, "error") %> prohibited this background from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @background.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                backgrounds_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/backgrounds/edit.html.erb
<%- model_class = Background -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/backgrounds/index.html.erb
<%- model_class = Background -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @backgrounds.each do |background| %>
      <tr>
        <td><%= link_to background.id, background_path(background) %></td>
        <td><%= background.name %></td>
        <td><%=l background.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_background_path(background), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      background_path(background),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_background_path,
            :class => 'btn btn-primary' %>

app/views/backgrounds/new.html.erb
<%- model_class = Background -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/backgrounds/show.html.erb
<%- model_class = Background -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @background.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              backgrounds_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_background_path(@background), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              background_path(@background),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>