config/routes.rb
Rails.application.routes.draw do
  resources :characters
  get '/characters/by_race/:race_id' => 'characters#by_race'
  resources :sub_class_jobs
  resources :class_jobs
  resources :backgrounds
  resources :sub_races
  resources :races
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :race
  belongs_to :sub_race
  belongs_to :class_job
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: %i[ show edit update destroy ]
  protect_from_forgery except: :by_race
  # GET /characters or /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1 or /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters or /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: "Character was successfully created." }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1 or /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: "Character was successfully updated." }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1 or /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: "Character was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def by_race
    @race = Race.find(params[:race_id])
    @sub_races = @race.sub_races
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def character_params
      params.require(:character).permit(:name, :level, :total_hp, :experience, :race_id, :sub_race_id, :class_job_id, :sub_class_job)
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_for @character, :html => { :class => "form-horizontal character" } do |f| %>

  <% if @character.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @character.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :player, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :player, :class => 'form-control' %>
    </div>
    <%=f.error_span(:player) %>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :level, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :level, :class => 'form-control' %>
    </div>
    <%=f.error_span(:level) %>
  </div>
  <div class="form-group">
    <%= f.label :total_hp, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :total_hp, :class => 'form-control' %>
    </div>
    <%=f.error_span(:total_hp) %>
  </div>
  <div class="form-group">
    <%= f.label :experience, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :experience, :class => 'form-control' %>
    </div>
    <%=f.error_span(:experience) %>
  </div>
  <div class="form-group">
    <%= f.label :race_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :race_id, Race.all.collect {|x| [x.name, x.id]}, {}, class: "form-control race"%>
    </div>
    <%=f.error_span(:race_id) %>
  </div>
  <div class="form-group">
    <%= f.label :sub_race_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :sub_race_id, '', {},:class => 'form-control sub_race'%>
    </div>
    <%=f.error_span(:sub_race_id) %>
  </div>
  <div class="form-group">
    <%= f.label :class_job_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :class_job_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:class_job_id) %>
  </div>
  <div class="form-group">
    <%= f.label :sub_class_job_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :sub_class_job_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:sub_class_job_id) %>
  </div>
  <div class="form-group">
    <%= f.label :background_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :background_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:background_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                characters_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>


<script type='text/javascript'>

    let race, sub_race

    if (!sub_race) sub_race = document.querySelector('.sub_race')
    if (!race) race = document.querySelector('.race')
    
    race.addEventListener('change', (event) => {

        let value = race.value
        
        console.log(value)
        const url = `/characters/by_race/${value}`;
        let xhr = new XMLHttpRequest();
        xhr.onreadystatechange = () => {
                if(xhr.readyState == 4){
                }
            }

        xhr.open('GET', url )

        xhr.send()
    });

    function setRace(input) {
      console.log(input.value)
      if (input.value == 'a'){
        race.removeAttribute("disabled")
      }else{
        race.setAttribute("disabled", "true")
      }
      console.log(race)
    };
    
</script>

app/views/characters/by_race.js.erb
$('.sub_race').empty();
$('.sub_race').append( $('<option>Select the Contact</option>'));
<% @sub_races.each do |sub_race| %>
  $('.sub_race').append($('<option value="<%= sub_race.id %>"><%= sub_race.name %></option>'));
<% end %>

app/views/characters/edit.html.erb
<%- model_class = Character -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/characters/index.html.erb
<%- model_class = Character -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:player) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:level) %></th>
      <th><%= model_class.human_attribute_name(:total_hp) %></th>
      <th><%= model_class.human_attribute_name(:experience) %></th>
      <th><%= model_class.human_attribute_name(:race_id) %></th>
      <th><%= model_class.human_attribute_name(:sub_race_id) %></th>
      <th><%= model_class.human_attribute_name(:class_job_id) %></th>
      <th><%= model_class.human_attribute_name(:sub_class_job_id) %></th>
      <th><%= model_class.human_attribute_name(:background_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= link_to character.id, character_path(character) %></td>
        <td><%= character.player %></td>
        <td><%= character.name %></td>
        <td><%= character.level %></td>
        <td><%= character.total_hp %></td>
        <td><%= character.experience %></td>
        <td><%= character.race_id %></td>
        <td><%= character.sub_race_id %></td>
        <td><%= character.class_job_id %></td>
        <td><%= character.sub_class_job_id %></td>
        <td><%= character.background_id %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_character_path(character), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      character_path(character),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_character_path,
            :class => 'btn btn-primary' %>

app/views/characters/new.html.erb
<%- model_class = Character -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/characters/show.html.erb
<%- model_class = Character -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:player) %>:</strong></dt>
  <dd><%= @character.player %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @character.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:level) %>:</strong></dt>
  <dd><%= @character.level %></dd>
  <dt><strong><%= model_class.human_attribute_name(:total_hp) %>:</strong></dt>
  <dd><%= @character.total_hp %></dd>
  <dt><strong><%= model_class.human_attribute_name(:experience) %>:</strong></dt>
  <dd><%= @character.experience %></dd>
  <dt><strong><%= model_class.human_attribute_name(:race_id) %>:</strong></dt>
  <dd><%= @character.race_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sub_race_id) %>:</strong></dt>
  <dd><%= @character.sub_race_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:class_job_id) %>:</strong></dt>
  <dd><%= @character.class_job_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sub_class_job_id) %>:</strong></dt>
  <dd><%= @character.sub_class_job_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:background_id) %>:</strong></dt>
  <dd><%= @character.background_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              characters_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_character_path(@character), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              character_path(@character),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>